-- Create ListingLocations table
CREATE TABLE IF NOT EXISTS "ListingLocations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "listingId" BIGINT NOT NULL REFERENCES "Listings"("id") ON DELETE CASCADE,
    "city" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE("listingId")
);

-- Note: You should migrate existing location data from Listings before dropping the column.
-- INSERT INTO "ListingLocations" ("listingId", "address", "city")
-- SELECT id, location, 'London' FROM "Listings" WHERE location IS NOT NULL;

-- Enable RLS
ALTER TABLE "ListingLocations" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view listing locations"
ON "ListingLocations" FOR SELECT USING (true);

CREATE POLICY "Authenticated users can insert listing locations"
ON "ListingLocations" FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can edit their own listing locations via Listings policy"
ON "ListingLocations" FOR ALL USING (
    EXISTS (SELECT 1 FROM "Listings" WHERE "Listings".id = "ListingLocations"."listingId" AND "Listings"."ownerId" = auth.uid())
);
