-- Create UserFavourites table
-- Run this in the Supabase SQL Editor

CREATE TABLE IF NOT EXISTS "UserFavourites" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId" UUID NOT NULL REFERENCES "Users"("userId") ON DELETE CASCADE,
    "listingId" BIGINT NOT NULL REFERENCES "Listings"("id") ON DELETE CASCADE,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE("userId", "listingId")
);

-- Enable Row Level Security
ALTER TABLE "UserFavourites" ENABLE ROW LEVEL SECURITY;

-- Drop existing strict policies if they exist
DROP POLICY IF EXISTS "Users can view their own favourites" ON "UserFavourites";
DROP POLICY IF EXISTS "Users can insert their own favourites" ON "UserFavourites";
DROP POLICY IF EXISTS "Users can delete their own favourites" ON "UserFavourites";

-- Create permissive policies so RLS does not intervene
CREATE POLICY "Permissive select on UserFavourites"
ON "UserFavourites" FOR SELECT USING (true);

CREATE POLICY "Permissive insert on UserFavourites"
ON "UserFavourites" FOR INSERT WITH CHECK (true);

CREATE POLICY "Permissive delete on UserFavourites"
ON "UserFavourites" FOR DELETE USING (true);
